/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.14.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as crons from "../crons.js";
import type * as image_image from "../image/image.js";
import type * as image_imageList from "../image/imageList.js";
import type * as notification_notification from "../notification/notification.js";
import type * as notification_notificationProduction from "../notification/notificationProduction.js";
import type * as notification_todoReminder from "../notification/todoReminder.js";
import type * as notification_todoReminderHelpers from "../notification/todoReminderHelpers.js";
import type * as user_crud from "../user/crud.js";
import type * as user_userPreference from "../user/userPreference.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  crons: typeof crons;
  "image/image": typeof image_image;
  "image/imageList": typeof image_imageList;
  "notification/notification": typeof notification_notification;
  "notification/notificationProduction": typeof notification_notificationProduction;
  "notification/todoReminder": typeof notification_todoReminder;
  "notification/todoReminderHelpers": typeof notification_todoReminderHelpers;
  "user/crud": typeof user_crud;
  "user/userPreference": typeof user_userPreference;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
