/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.14.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as crons from "../crons.js";
import type * as image from "../image.js";
import type * as imageList from "../imageList.js";
import type * as notification from "../notification.js";
import type * as notificationProduction from "../notificationProduction.js";
import type * as todoReminder from "../todoReminder.js";
import type * as todoReminderHelpers from "../todoReminderHelpers.js";
import type * as user_crud from "../user/crud.js";
import type * as user_userPreference from "../user/userPreference.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  crons: typeof crons;
  image: typeof image;
  imageList: typeof imageList;
  notification: typeof notification;
  notificationProduction: typeof notificationProduction;
  todoReminder: typeof todoReminder;
  todoReminderHelpers: typeof todoReminderHelpers;
  "user/crud": typeof user_crud;
  "user/userPreference": typeof user_userPreference;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
